Repository SonarSource/sonar-go, pull requests merged in 2018-04, with the labels that each got.

#191 Fix FPs on S4144
  common-rule-engine/src/main/java/org/sonar/commonruleengine/checks/NoIdenticalFunctionsCheck.java
  common-rule-engine/src/main/java/org/sonar/commonruleengine/checks/TooManyParametersCheck.java
  common-rule-engine/src/main/java/org/sonar/uast/UastNode.java
  common-rule-engine/src/main/java/org/sonar/uast/helpers/FunctionLike.java
  common-rule-engine/src/test/files/checks/go/AllBranchesAreIdenticalCheck/AllBranchesAreIdenticalCheck.go.uast.json
  common-rule-engine/src/test/files/checks/go/FunctionCognitiveComplexityCheck/FunctionCognitiveComplexityCheck.go.uast.json
  common-rule-engine/src/test/files/checks/go/NestedSwitchCheck/NestedSwitchCheck.go.uast.json
  common-rule-engine/src/test/files/checks/go/NoIdenticalConditionsCheck/NoIdenticalConditionsCheck.go.uast.json
  common-rule-engine/src/test/files/checks/go/NoIdenticalConditionsCheck/NoIdenticalConditionsCheckSwitch.go.uast.json
  common-rule-engine/src/test/files/checks/go/NoIdenticalFunctionsCheck/NoIdenticalFunctionsCheck.go
  common-rule-engine/src/test/files/checks/go/NoIdenticalFunctionsCheck/NoIdenticalFunctionsCheck.go.uast.json
  common-rule-engine/src/test/files/checks/go/NoSelfAssignmentCheck/NoSelfAssignmentCheck.go.uast.json
  common-rule-engine/src/test/files/checks/go/RedundantBooleanLiteralCheck/RedundantBooleanLiteralCheck.go.uast.json
  common-rule-engine/src/test/files/checks/go/SwitchDefaultLocationCheck/SwitchDefaultLocationCheck.go.uast.json
  common-rule-engine/src/test/files/checks/go/SwitchWithoutDefaultCheck/SwitchWithoutDefaultCheck.go.uast.json
  common-rule-engine/src/test/files/checks/go/TooManyParametersCheck/TooManyParametersCheck.go.uast.json
  common-rule-engine/src/test/files/checks/go/TooManyParametersCheck/TooManyParametersCheckMax3.go.uast.json
  common-rule-engine/src/test/files/checks/go/UnconditionalJumpStatementCheck/UnconditionalJumpStatementCheck.go.uast.json
  its/ruling/src/test/expected/go-S4144.json
  uast-generator-go/generate_source.go
  uast-generator-go/goparser_test.go
  uast-generator-java/src/main/java/org/sonar/uast/generator/java/Generator.java
  uast-generator-java/src/main/java/org/sonar/uast/generator/java/UastNode.java
  uast-generator-java/src/test/files/reference.java.uast.json
Labels: in progress

#197 Fix ruling in developer environment
  README.md
  its/plugin/tests/build.gradle
  its/plugin/tests/src/test/java/com/sonar/it/go/Tests.java
  its/ruling/build.gradle
  its/ruling/src/test/java/org/sonar/go/GoRulingTest.java
Labels: in progress

#198 Analysis should never fail
  common-rule-engine/src/main/java/org/sonar/commonruleengine/Engine.java
  sonar-go-plugin/src/main/java/org/sonar/go/plugin/GoSensor.java
  sonar-go-plugin/src/test/java/org/sonar/go/plugin/GoSensorTest.java
Labels: in progress

#199 Improve S3776 (CognitiveComplexity) +1 for goto, break, continue to label
  common-rule-engine/src/main/java/org/sonar/commonruleengine/CognitiveComplexity.java
  common-rule-engine/src/main/java/org/sonar/uast/UastNode.java
  common-rule-engine/src/main/java/org/sonar/uast/helpers/BranchLike.java
  common-rule-engine/src/test/files/checks/go/FunctionCognitiveComplexityCheck/FunctionCognitiveComplexityCheck.go
  common-rule-engine/src/test/files/checks/go/FunctionCognitiveComplexityCheck/FunctionCognitiveComplexityCheck.go.uast.json
  common-rule-engine/src/test/files/checks/go/WrongAssignmentOperatorCheck/WrongAssignmentOperatorCheck.go.uast.json
  common-rule-engine/src/test/files/checks/java/FunctionCognitiveComplexityCheck/FunctionCognitiveComplexityCheck.java
  its/ruling/src/test/expected/go-S1110.json
  its/ruling/src/test/expected/go-S3776.json
  sonar-go-plugin/src/test/resources/org/sonar/go/plugin/CpdVisitorTest/lets.go.uast.json
  uast-generator-go/generate_source.go
  uast-generator-go/goparser.go
  uast-generator-java/src/main/java/org/sonar/uast/generator/java/Generator.java
  uast-generator-java/src/main/java/org/sonar/uast/generator/java/UastNode.java
Labels: in progress

#200 Make it release ready
  build.gradle
  common-rule-engine/build.gradle
  gradle.properties
  sonar-go-plugin/build.gradle
  travis.sh
  uast-generator-java/build.gradle
Labels: in progress

#201 Update rules metadata and add sonarpedia.json using rule-api 1.18.0.1055
  sonar-go-plugin/src/main/resources/org/sonar/l10n/go/rules/go/S107.html
  sonar-go-plugin/src/main/resources/org/sonar/l10n/go/rules/go/S107.json
  sonar-go-plugin/src/main/resources/org/sonar/l10n/go/rules/go/S1125.html
  sonar-go-plugin/src/main/resources/org/sonar/l10n/go/rules/go/S1125.json
  sonar-go-plugin/src/main/resources/org/sonar/l10n/go/rules/go/S1451.html
  sonar-go-plugin/src/main/resources/org/sonar/l10n/go/rules/go/S1451.json
  sonar-go-plugin/src/main/resources/org/sonar/l10n/go/rules/go/S1656.html
  sonar-go-plugin/src/main/resources/org/sonar/l10n/go/rules/go/S1656.json
  sonar-go-plugin/src/main/resources/org/sonar/l10n/go/rules/go/S1751.html
  sonar-go-plugin/src/main/resources/org/sonar/l10n/go/rules/go/S1751.json
  sonar-go-plugin/src/main/resources/org/sonar/l10n/go/rules/go/S1764.html
  sonar-go-plugin/src/main/resources/org/sonar/l10n/go/rules/go/S1764.json
  sonar-go-plugin/src/main/resources/org/sonar/l10n/go/rules/go/S1821.json
  sonar-go-plugin/src/main/resources/org/sonar/l10n/go/rules/go/S1862.html
  sonar-go-plugin/src/main/resources/org/sonar/l10n/go/rules/go/S1862.json
  sonar-go-plugin/src/main/resources/org/sonar/l10n/go/rules/go/S2068.html
  sonar-go-plugin/src/main/resources/org/sonar/l10n/go/rules/go/S2068.json
  sonar-go-plugin/src/main/resources/org/sonar/l10n/go/rules/go/S3923.html
  sonar-go-plugin/src/main/resources/org/sonar/l10n/go/rules/go/S3923.json
  sonar-go-plugin/src/main/resources/org/sonar/l10n/go/rules/go/S4144.html
  sonar-go-plugin/src/main/resources/org/sonar/l10n/go/rules/go/S4144.json
  sonarpedia.json
Labels: in progress

#203 Change version to 0.2-SNAPSHOT
  gradle.properties
Labels: in progress

#202 Add badges to README
  README.md
Labels: in progress

#194 create go uast on the fly
  common-rule-engine/build.gradle
  common-rule-engine/src/test/files/checks/go/AllBranchesAreIdenticalCheck/AllBranchesAreIdenticalCheck.go.uast.json
  common-rule-engine/src/test/files/checks/go/BinaryOperatorIdenticalExpressionsCheck/BinaryOperatorIdenticalExpressionsCheck.go.uast.json
  common-rule-engine/src/test/files/checks/go/FileHeaderCheck/FileHeaderCheck.go.uast.json
  common-rule-engine/src/test/files/checks/go/FileHeaderCheck/FileHeaderCheckBeforeHeader.go.uast.json
  common-rule-engine/src/test/files/checks/go/FileHeaderCheck/FileHeaderCheckYear.go.uast.json
  common-rule-engine/src/test/files/checks/go/FileHeaderCheck/FileHeaderCheckYearNoIssue.go.uast.json
  common-rule-engine/src/test/files/checks/go/FunctionCognitiveComplexityCheck/FunctionCognitiveComplexityCheck.go.uast.json
  common-rule-engine/src/test/files/checks/go/NestedSwitchCheck/NestedSwitchCheck.go.uast.json
  common-rule-engine/src/test/files/checks/go/NoHardcodedCredentialsCheck/NoHardcodedCredentialsCheck.go.uast.json
  common-rule-engine/src/test/files/checks/go/NoIdenticalConditionsCheck/NoIdenticalConditionsCheck.go.uast.json
  common-rule-engine/src/test/files/checks/go/NoIdenticalConditionsCheck/NoIdenticalConditionsCheckSwitch.go.uast.json
  common-rule-engine/src/test/files/checks/go/NoIdenticalFunctionsCheck/NoIdenticalFunctionsCheck.go.uast.json
  common-rule-engine/src/test/files/checks/go/NoSelfAssignmentCheck/NoSelfAssignmentCheck.go.uast.json
  common-rule-engine/src/test/files/checks/go/RedundantBooleanLiteralCheck/RedundantBooleanLiteralCheck.go.uast.json
  common-rule-engine/src/test/files/checks/go/RedundantParenthesesCheck/RedundantParenthesesCheck.go.uast.json
  common-rule-engine/src/test/files/checks/go/SwitchDefaultLocationCheck/SwitchDefaultLocationCheck.go.uast.json
  common-rule-engine/src/test/files/checks/go/SwitchWithoutDefaultCheck/SwitchWithoutDefaultCheck.go.uast.json
  common-rule-engine/src/test/files/checks/go/TooManyParametersCheck/TooManyParametersCheck.go.uast.json
  common-rule-engine/src/test/files/checks/go/TooManyParametersCheck/TooManyParametersCheckMax3.go.uast.json
  common-rule-engine/src/test/files/checks/go/UnconditionalJumpStatementCheck/UnconditionalJumpStatementCheck.go.uast.json
  common-rule-engine/src/test/java/org/sonar/commonruleengine/checks/TestUtils.java
Labels: in progress

#204 Import our own go source code coverage into next.sonarqube.com
  travis.sh
  uast-generator-go/build.gradle
Labels: in progress

#205 Minor README improvements
  README.md
Labels: in progress

#207 Fix entries in jar manifest
  build.gradle
  sonar-go-plugin/build.gradle
Labels: in progress

#208 Update rules metadata using rule-api 1.18.0.1055 (replace S131 by S4524 in sonar way)
  sonar-go-plugin/src/main/resources/org/sonar/l10n/go/rules/go/S131.html
  sonar-go-plugin/src/main/resources/org/sonar/l10n/go/rules/go/Sonar_way_profile.json
  sonarpedia.json
Labels: in progress

#206 Support "sonar.go.file.suffixes" property.
  sonar-go-plugin/src/main/java/org/sonar/go/plugin/GoLanguage.java
  sonar-go-plugin/src/main/java/org/sonar/go/plugin/GoPlugin.java
  sonar-go-plugin/src/test/java/org/sonar/go/plugin/GoLanguageTest.java
  sonar-go-plugin/src/test/java/org/sonar/go/plugin/GoPluginTest.java
Labels: in progress

#213 Bump version number
  gradle.properties
Labels: in progress

#220 Add Go parser kinds: FOR, FOR_KEYWORD, FOR_INIT, FOR_UPDATE, FOR_BODY
  common-rule-engine/src/main/java/org/sonar/commonruleengine/checks/UnconditionalJumpStatementCheck.java
  common-rule-engine/src/main/java/org/sonar/uast/UastNode.java
  common-rule-engine/src/main/java/org/sonar/uast/helpers/ForLike.java
  common-rule-engine/src/test/files/kinds/ForStatement1.go
  common-rule-engine/src/test/files/kinds/ForStatement2.go
  common-rule-engine/src/test/files/kinds/ForStatement3.go
  common-rule-engine/src/test/files/kinds/Loop.go
  common-rule-engine/src/test/java/org/sonar/uast/helpers/ForLikeTest.java
  uast-generator-go/generate_source.go
  uast-generator-go/goparser.go
  uast-generator-go/goparser_test.go
Labels: review

#219 Fix #83 RSPEC-1479 switch with too many cases
  common-rule-engine/src/main/java/org/sonar/commonruleengine/checks/SwitchWithTooManyCaseCheck.java
  common-rule-engine/src/test/files/checks/SwitchWithTooManyCaseCheck/SwitchWithTooManyCaseCheck.go
  common-rule-engine/src/test/files/checks/SwitchWithTooManyCaseCheck/SwitchWithTooManyCaseCheck.java
  common-rule-engine/src/test/files/checks/SwitchWithTooManyCaseCheck/SwitchWithTooManyCaseCheckMax5.go
  common-rule-engine/src/test/files/checks/SwitchWithTooManyCaseCheck/SwitchWithTooManyCaseCheckMax5.java
  common-rule-engine/src/test/java/org/sonar/commonruleengine/checks/SwitchWithTooManyCaseCheckTest.java
  its/ruling/src/test/expected/go-S1479.json
  sonar-go-plugin/src/main/java/org/sonar/go/plugin/GoChecks.java
  sonar-go-plugin/src/main/resources/org/sonar/l10n/go/rules/go/S1479.html
  sonar-go-plugin/src/main/resources/org/sonar/l10n/go/rules/go/S1479.json
  sonar-go-plugin/src/main/resources/org/sonar/l10n/go/rules/go/Sonar_way_profile.json
Labels: in progress

#223 Add kind inheritance related to CONTROL_FLOW and JUMP
  common-rule-engine/src/main/java/org/sonar/uast/UastNode.java
  common-rule-engine/src/test/java/org/sonar/commonruleengine/checks/TestUtils.java
  common-rule-engine/src/test/java/org/sonar/uast/UastNodeTest.java
Labels: review

#222 Complete Java Uast
  common-rule-engine/src/main/java/org/sonar/uast/UastNode.java
  common-rule-engine/src/main/java/org/sonar/uast/helpers/ForLike.java
  common-rule-engine/src/test/files/checks/FunctionCognitiveComplexityCheck/FunctionCognitiveComplexityCheck.java
  common-rule-engine/src/test/files/checks/UnconditionalJumpStatementCheck/UnconditionalJumpStatementCheck.java
  uast-generator-go/generate_source.go
  uast-generator-go/goparser.go
  uast-generator-go/goparser_test.go
  uast-generator-java/build.gradle
  uast-generator-java/src/main/java/org/sonar/uast/generator/java/Generator.java
  uast-generator-java/src/main/java/org/sonar/uast/generator/java/UastNode.java
  uast-generator-java/src/test/files/kinds/annotations.java
  uast-generator-java/src/test/files/kinds/annotations.java.uast.json
  uast-generator-java/src/test/files/kinds/assignments.java
  uast-generator-java/src/test/files/kinds/assignments.java.uast.json
  uast-generator-java/src/test/files/kinds/comments.java
  uast-generator-java/src/test/files/kinds/comments.java.uast.json
  uast-generator-java/src/test/files/kinds/controlflow.java
  uast-generator-java/src/test/files/kinds/controlflow.java.uast.json
  uast-generator-java/src/test/files/kinds/expressions.java
  uast-generator-java/src/test/files/kinds/expressions.java.uast.json
  uast-generator-java/src/test/files/kinds/generics.java
  uast-generator-java/src/test/files/kinds/generics.java.uast.json
  uast-generator-java/src/test/files/kinds/lambda.java
  uast-generator-java/src/test/files/kinds/lambda.java.uast.json
  uast-generator-java/src/test/files/kinds/literals.java
  uast-generator-java/src/test/files/kinds/literals.java.uast.json
  uast-generator-java/src/test/files/kinds/methods.java
  uast-generator-java/src/test/files/kinds/methods.java.uast.json
  uast-generator-java/src/test/files/kinds/operators.java
  uast-generator-java/src/test/files/kinds/operators.java.uast.json
  uast-generator-java/src/test/files/kinds/statements.java
  uast-generator-java/src/test/files/kinds/statements.java.uast.json
  uast-generator-java/src/test/files/reference.java.uast.json
  uast-generator-java/src/test/java/org/sonar/uast/generator/java/GeneratorTest.java
  uast-generator-java/src/test/java/org/sonar/uast/generator/java/UastKindsTest.java
Labels: in progress

#226 Fix #93 S2761 double prefix operator rule
  common-rule-engine/src/main/java/org/sonar/commonruleengine/checks/DoublePrefixOperatorCheck.java
  common-rule-engine/src/test/files/checks/DoublePrefixOperatorCheck/DoublePrefixOperatorCheck.go
  common-rule-engine/src/test/files/checks/DoublePrefixOperatorCheck/DoublePrefixOperatorCheck.java
  common-rule-engine/src/test/java/org/sonar/commonruleengine/checks/DoublePrefixOperatorCheckTest.java
  sonar-go-plugin/src/main/java/org/sonar/go/plugin/GoChecks.java
  sonar-go-plugin/src/main/resources/org/sonar/l10n/go/rules/go/S2761.html
  sonar-go-plugin/src/main/resources/org/sonar/l10n/go/rules/go/S2761.json
  sonar-go-plugin/src/main/resources/org/sonar/l10n/go/rules/go/Sonar_way_profile.json
  uast-generator-java/src/main/java/org/sonar/uast/generator/java/UastNode.java
Labels: in progress

#229 Remove unary expressions kinds from operator
  uast-generator-java/src/main/java/org/sonar/uast/generator/java/UastNode.java
  uast-generator-java/src/test/files/kinds/operators.java
  uast-generator-java/src/test/files/kinds/operators.java.uast.json
Labels: review

#230 Assert go parser kinds are subset of common kinds
  common-rule-engine/src/main/java/org/sonar/uast/UastNode.java
  common-rule-engine/src/test/files/kinds/Argument.go
  common-rule-engine/src/test/files/kinds/Arguments.go
  common-rule-engine/src/test/files/kinds/Call.go
  common-rule-engine/src/test/files/kinds/Declaration.go
  common-rule-engine/src/test/files/kinds/MemberSelect.go
  common-rule-engine/src/test/files/kinds/Switch.go
  common-rule-engine/src/test/files/kinds/SwitchCase.go
  common-rule-engine/src/test/files/kinds/SwitchCondition.go
  common-rule-engine/src/test/java/org/sonar/commonruleengine/MetricsVisitorTest.java
  common-rule-engine/src/test/java/org/sonar/commonruleengine/checks/TestUtils.java
  common-rule-engine/src/test/java/org/sonar/uast/UastNodeTest.java
  uast-generator-go/generate_source.go
  uast-generator-go/goparser.go
  uast-generator-go/goparser_test.go
  uast-generator-go/json_test.go
  uast-generator-go/main.go
Labels: in progress

#232 Add kinds for literals
  common-rule-engine/src/main/java/org/sonar/uast/UastNode.java
  uast-generator-java/src/main/java/org/sonar/uast/generator/java/Generator.java
  uast-generator-java/src/main/java/org/sonar/uast/generator/java/UastNode.java
  uast-generator-java/src/test/files/kinds/assignments.java.uast.json
  uast-generator-java/src/test/files/kinds/controlflow.java.uast.json
  uast-generator-java/src/test/files/kinds/expressions.java.uast.json
  uast-generator-java/src/test/files/kinds/lambda.java.uast.json
  uast-generator-java/src/test/files/kinds/literals.java
  uast-generator-java/src/test/files/kinds/literals.java.uast.json
  uast-generator-java/src/test/files/kinds/methods.java.uast.json
  uast-generator-java/src/test/files/kinds/operators.java.uast.json
  uast-generator-java/src/test/files/kinds/statements.java.uast.json
  uast-generator-java/src/test/files/reference.java.uast.json
Labels: in progress

#233 Add kinds for parameters
  uast-generator-java/build.gradle
  uast-generator-java/src/main/java/org/sonar/uast/generator/java/Generator.java
  uast-generator-java/src/main/java/org/sonar/uast/generator/java/UastNode.java
  uast-generator-java/src/test/files/kinds/assignments.java.uast.json
  uast-generator-java/src/test/files/kinds/comments.java.uast.json
  uast-generator-java/src/test/files/kinds/controlflow.java.uast.json
  uast-generator-java/src/test/files/kinds/expressions.java.uast.json
  uast-generator-java/src/test/files/kinds/methods.java.uast.json
  uast-generator-java/src/test/files/kinds/operators.java.uast.json
  uast-generator-java/src/test/files/kinds/statements.java.uast.json
  uast-generator-java/src/test/files/reference.java.uast.json
  uast-generator-java/src/test/java/org/sonar/uast/generator/java/UastKindsTest.java
Labels: in progress

#236 Add UAST reference documentation
  README.md
  common-rule-engine/docs/UAST-Kinds.md
  common-rule-engine/docs/UAST-Reference.md
  common-rule-engine/src/main/java/org/sonar/uast/UastNode.java
  common-rule-engine/src/test/java/org/sonar/uast/DocumentationTest.java
  sonar-go-plugin/src/test/resources/org/sonar/go/plugin/CpdVisitorTest/lets.go.uast.json
  uast-generator-java/src/main/java/org/sonar/uast/generator/java/Generator.java
Labels: in progress

#238 BinaryExpressionLike should not used children position to resolve operand
  common-rule-engine/build.gradle
  common-rule-engine/docs/UAST-Kinds.md
  common-rule-engine/src/main/java/org/sonar/commonruleengine/CognitiveComplexity.java
  common-rule-engine/src/main/java/org/sonar/commonruleengine/checks/BinaryOperatorIdenticalExpressionsCheck.java
  common-rule-engine/src/main/java/org/sonar/commonruleengine/checks/RedundantBooleanLiteralCheck.java
  common-rule-engine/src/main/java/org/sonar/uast/UastNode.java
  common-rule-engine/src/main/java/org/sonar/uast/helpers/BinaryExpressionLike.java
  common-rule-engine/src/test/files/checks/WrongAssignmentOperatorCheck/WrongAssignmentOperatorCheck.go.uast.json
  common-rule-engine/src/test/java/org/sonar/uast/DocGenerator.java
  common-rule-engine/src/test/java/org/sonar/uast/UastNodeTest.java
  common-rule-engine/src/test/java/org/sonar/uast/helpers/BinaryExpressionLikeTest.java
  uast-generator-go/generate_source.go
  uast-generator-go/goparser.go
  uast-generator-go/goparser_test.go
  uast-generator-java/src/main/java/org/sonar/uast/generator/java/Generator.java
  uast-generator-java/src/main/java/org/sonar/uast/generator/java/UastNode.java
  uast-generator-java/src/test/files/kinds/controlflow.java.uast.json
  uast-generator-java/src/test/files/kinds/generics.java.uast.json
  uast-generator-java/src/test/files/kinds/imports.java.uast.json
  uast-generator-java/src/test/files/kinds/lambda.java.uast.json
  uast-generator-java/src/test/files/kinds/methods.java.uast.json
  uast-generator-java/src/test/files/kinds/operators.java.uast.json
Labels: in progress

#241 Make ElseLike innerclass of IfLike
  common-rule-engine/src/main/java/org/sonar/commonruleengine/CognitiveComplexity.java
  common-rule-engine/src/main/java/org/sonar/commonruleengine/checks/AllBranchesAreIdenticalCheck.java
  common-rule-engine/src/main/java/org/sonar/uast/helpers/ElseLike.java
  common-rule-engine/src/main/java/org/sonar/uast/helpers/IfLike.java
  common-rule-engine/src/test/java/org/sonar/uast/helpers/IfLikeTest.java
Labels: review

#244 Rename modulo to remainder
  common-rule-engine/docs/UAST-Kinds.md
  common-rule-engine/src/main/java/org/sonar/uast/UastNode.java
  uast-generator-go/goparser.go
  uast-generator-go/goparser_test.go
  uast-generator-java/src/main/java/org/sonar/uast/generator/java/Generator.java
  uast-generator-java/src/main/java/org/sonar/uast/generator/java/UastNode.java
  uast-generator-java/src/test/files/kinds/operators.java.uast.json
Labels: in progress

#245 Close input stream for input file
  sonar-go-plugin/src/main/java/org/sonar/go/plugin/GoSensor.java
Labels: bug, in progress

#243 Simplify FunctionLike to use getDescendants(...) with adequate parameters
  common-rule-engine/src/main/java/org/sonar/uast/helpers/FunctionLike.java
Labels: review

#242 Assignment kinds should not be on operator itself
  common-rule-engine/docs/UAST-Kinds.md
  common-rule-engine/src/main/java/org/sonar/uast/UastNode.java
  common-rule-engine/src/test/files/checks/NoSelfAssignmentCheck/NoSelfAssignmentCheck.java
  uast-generator-java/src/main/java/org/sonar/uast/generator/java/Generator.java
  uast-generator-java/src/main/java/org/sonar/uast/generator/java/UastNode.java
  uast-generator-java/src/test/files/kinds/assignments.java.uast.json
Labels: review

#246 Remove no longer necessary workaround for continue
  uast-generator-java/src/main/java/org/sonar/uast/generator/java/Generator.java
  uast-generator-java/src/test/files/kinds/controlflow.java.uast.json
Labels: in progress

#247 Report On Comments
  common-rule-engine/src/test/java/org/sonar/commonruleengine/checks/TestUtils.java
Labels: review

#251 Exclude generated files from ruling analysis
  its/ruling/src/test/expected/go-S1125.json
  its/ruling/src/test/expected/go-S1479.json
  its/ruling/src/test/expected/go-S3776.json
  its/ruling/src/test/java/org/sonar/go/GoRulingTest.java
Labels: in progress

#253 Drop unused CheckList class
  common-rule-engine/src/main/java/org/sonar/commonruleengine/checks/CheckList.java
Labels: review

#259 Fix reporting to handle comments
  sonar-go-plugin/src/main/java/org/sonar/go/plugin/utils/PluginApiUtils.java
  sonar-go-plugin/src/test/java/org/sonar/go/plugin/utils/PluginApiUtilsTest.java
Labels: bug, review

#249 Rule S1313: IP addresses should not be hardcoded
  common-rule-engine/src/main/java/org/sonar/commonruleengine/checks/HardcodedIpAddressCheck.java
  common-rule-engine/src/test/files/checks/HardcodedIpAddressCheck/HardcodedIpAddressCheck.go
  common-rule-engine/src/test/files/checks/HardcodedIpAddressCheck/HardcodedIpAddressCheck.java
  common-rule-engine/src/test/java/org/sonar/commonruleengine/checks/HardcodedIpAddressCheckTest.java
  its/ruling/src/test/expected/go-S1313.json
  sonar-go-plugin/src/main/java/org/sonar/go/plugin/GoChecks.java
  sonar-go-plugin/src/main/resources/org/sonar/l10n/go/rules/go/S1313.html
  sonar-go-plugin/src/main/resources/org/sonar/l10n/go/rules/go/S1313.json
  sonar-go-plugin/src/main/resources/org/sonar/l10n/go/rules/go/Sonar_way_profile.json
Labels: in progress, new-rule

#260 Rule S1314: Octal values should not be used
  common-rule-engine/src/main/java/org/sonar/commonruleengine/checks/OctalNumberCheck.java
  common-rule-engine/src/test/files/checks/OctalNumberCheck/OctalNumberCheck.go
  common-rule-engine/src/test/files/checks/OctalNumberCheck/OctalNumberCheck.java
  common-rule-engine/src/test/java/org/sonar/commonruleengine/checks/OctalNumberCheckTest.java
  its/ruling/src/test/expected/go-S1314.json
  sonar-go-plugin/src/main/java/org/sonar/go/plugin/GoChecks.java
  sonar-go-plugin/src/main/resources/org/sonar/l10n/go/rules/go/S1314.html
  sonar-go-plugin/src/main/resources/org/sonar/l10n/go/rules/go/S1314.json
Labels: in progress

#256 Rule S1134: Track uses of "FIXME" tags
  common-rule-engine/src/main/java/org/sonar/commonruleengine/checks/FixMeTagPresenceCheck.java
  common-rule-engine/src/test/files/checks/FixMeTagPresenceCheck/FixMeTagPresenceCheck.go
  common-rule-engine/src/test/files/checks/FixMeTagPresenceCheck/FixMeTagPresenceCheck.java
  common-rule-engine/src/test/java/org/sonar/commonruleengine/checks/FixMeTagPresenceCheckTest.java
  its/ruling/src/test/expected/go-S1134.json
  sonar-go-plugin/src/main/java/org/sonar/go/plugin/GoChecks.java
  sonar-go-plugin/src/main/resources/org/sonar/l10n/go/rules/go/S1134.html
  sonar-go-plugin/src/main/resources/org/sonar/l10n/go/rules/go/S1134.json
  sonar-go-plugin/src/main/resources/org/sonar/l10n/go/rules/go/Sonar_way_profile.json
Labels: in progress

#262 Rule S1135: Track uses of "TODO" tags
  common-rule-engine/src/main/java/org/sonar/commonruleengine/checks/TodoTagPresenceCheck.java
  common-rule-engine/src/test/files/checks/TodoTagPresenceCheck/TodoTagPresenceCheck.go
  common-rule-engine/src/test/files/checks/TodoTagPresenceCheck/TodoTagPresenceCheck.java
  common-rule-engine/src/test/java/org/sonar/commonruleengine/checks/TodoTagPresenceCheckTest.java
  its/ruling/src/test/expected/go-S1135.json
  sonar-go-plugin/src/main/java/org/sonar/go/plugin/GoChecks.java
  sonar-go-plugin/src/main/resources/org/sonar/l10n/go/rules/go/S1135.html
  sonar-go-plugin/src/main/resources/org/sonar/l10n/go/rules/go/S1135.json
  sonar-go-plugin/src/main/resources/org/sonar/l10n/go/rules/go/Sonar_way_profile.json
Labels: review

#255 Kinds ad hoc validation tested with SWITCH
  common-rule-engine/src/main/java/org/sonar/commonruleengine/Engine.java
  common-rule-engine/src/main/java/org/sonar/commonruleengine/EngineContext.java
  common-rule-engine/src/main/java/org/sonar/commonruleengine/checks/Check.java
  common-rule-engine/src/main/java/org/sonar/uast/UastNode.java
  common-rule-engine/src/main/java/org/sonar/uast/Visitor.java
  common-rule-engine/src/main/java/org/sonar/uast/validators/CaseValidator.java
  common-rule-engine/src/main/java/org/sonar/uast/validators/DefaultCaseValidator.java
  common-rule-engine/src/main/java/org/sonar/uast/validators/SwitchValidator.java
  common-rule-engine/src/main/java/org/sonar/uast/validators/Validator.java
  common-rule-engine/src/main/java/org/sonar/uast/validators/ValidatorList.java
  common-rule-engine/src/main/java/org/sonar/uast/validators/package-info.java
  common-rule-engine/src/test/files/checks/SwitchDefaultLocationCheck/SwitchDefaultLocationCheck.go
  common-rule-engine/src/test/java/org/sonar/commonruleengine/MetricsVisitorTest.java
  common-rule-engine/src/test/java/org/sonar/uast/validators/CaseValidatorTest.java
  common-rule-engine/src/test/java/org/sonar/uast/validators/DefaultCaseValidatorTest.java
  common-rule-engine/src/test/java/org/sonar/uast/validators/SwitchValidatorTest.java
  common-rule-engine/src/test/java/org/sonar/uast/validators/ValidatorTestUtils.java
  sonar-go-plugin/src/main/java/org/sonar/go/plugin/GoSensor.java
  uast-generator-go/generate_source.go
  uast-generator-java/src/main/java/org/sonar/uast/generator/java/Generator.java
  uast-generator-java/src/test/files/kinds/annotations.java.uast.json
  uast-generator-java/src/test/files/kinds/arrays.java.uast.json
  uast-generator-java/src/test/files/kinds/assignments.java.uast.json
  uast-generator-java/src/test/files/kinds/comments.java.uast.json
  uast-generator-java/src/test/files/kinds/controlflow.java.uast.json
  uast-generator-java/src/test/files/kinds/enums.java.uast.json
  uast-generator-java/src/test/files/kinds/expressions.java.uast.json
  uast-generator-java/src/test/files/kinds/generics.java.uast.json
  uast-generator-java/src/test/files/kinds/imports.java.uast.json
  uast-generator-java/src/test/files/kinds/instanceof.java.uast.json
  uast-generator-java/src/test/files/kinds/lambda.java.uast.json
  uast-generator-java/src/test/files/kinds/literals.java.uast.json
  uast-generator-java/src/test/files/kinds/memberselect.java.uast.json
  uast-generator-java/src/test/files/kinds/methods.java.uast.json
  uast-generator-java/src/test/files/kinds/operators.java.uast.json
  uast-generator-java/src/test/files/kinds/package.java.uast.json
  uast-generator-java/src/test/files/kinds/statements.java.uast.json
  uast-generator-java/src/test/files/kinds/typecast.java.uast.json
  uast-generator-java/src/test/files/kinds/variable.java.uast.json
  uast-generator-java/src/test/files/reference.java.uast.json
Labels: KIND validation, in progress

#263 Adapt to rule-api 1.19, options recorded in sonarpedia.json
  sonarpedia.json
Labels: in progress

#265 Node builder experiment
  common-rule-engine/src/test/java/org/sonar/uast/validators/IfValidatorTest.java
  common-rule-engine/src/test/java/org/sonar/uast/validators/ValidatorTestUtils.java
Labels: in progress

#271 Log at error level exceptions during analysis
  sonar-go-plugin/src/main/java/org/sonar/go/plugin/GoSensor.java
  sonar-go-plugin/src/test/java/org/sonar/go/plugin/GoSensorTest.java
Labels: in progress

#273 Rule S103: Lines should not be too long
  common-rule-engine/src/main/java/org/sonar/commonruleengine/Engine.java
  common-rule-engine/src/main/java/org/sonar/commonruleengine/EngineContext.java
  common-rule-engine/src/main/java/org/sonar/commonruleengine/Issue.java
  common-rule-engine/src/main/java/org/sonar/commonruleengine/checks/Check.java
  common-rule-engine/src/main/java/org/sonar/commonruleengine/checks/FileHeaderCheck.java
  common-rule-engine/src/main/java/org/sonar/commonruleengine/checks/TooLongLineCheck.java
  common-rule-engine/src/test/files/checks/TooLongLineCheck/TooLongLineCheck.go
  common-rule-engine/src/test/files/checks/TooLongLineCheck/TooLongLineCheck.java
  common-rule-engine/src/test/java/org/sonar/commonruleengine/checks/TestUtils.java
  common-rule-engine/src/test/java/org/sonar/commonruleengine/checks/TooLongLineCheckTest.java
  its/ruling/src/test/expected/go-S103.json
  sonar-go-plugin/src/main/java/org/sonar/go/plugin/GoChecks.java
  sonar-go-plugin/src/main/java/org/sonar/go/plugin/GoSensor.java
  sonar-go-plugin/src/main/resources/org/sonar/l10n/go/rules/go/S103.html
  sonar-go-plugin/src/main/resources/org/sonar/l10n/go/rules/go/S103.json
  sonar-go-plugin/src/test/java/org/sonar/go/plugin/GoSensorTest.java
Labels: in progress

#277 Fix #71 RSPEC-126 if else if without ending else
  common-rule-engine/src/main/java/org/sonar/commonruleengine/checks/IfElseIfWithoutElseCheck.java
  common-rule-engine/src/test/files/checks/IfElseIfWithoutElseCheck/IfElseIfWithoutElseCheck.go
  common-rule-engine/src/test/java/org/sonar/commonruleengine/checks/IfElseIfWithoutElseCheckTest.java
  its/ruling/src/test/expected/go-S126.json
  sonar-go-plugin/src/main/java/org/sonar/go/plugin/GoChecks.java
  sonar-go-plugin/src/main/resources/org/sonar/l10n/go/rules/go/S126.html
  sonar-go-plugin/src/main/resources/org/sonar/l10n/go/rules/go/S126.json
Labels: in progress

#274 RSPEC-1186 Methods should not be empty
  common-rule-engine/src/main/java/org/sonar/commonruleengine/checks/EmptyFunctionCheck.java
  common-rule-engine/src/test/files/checks/EmptyFunctionCheck/EmptyFunctionCheck.go
  common-rule-engine/src/test/files/checks/EmptyFunctionCheck/EmptyFunctionCheck.java
  common-rule-engine/src/test/java/org/sonar/commonruleengine/checks/EmptyFunctionCheckTest.java
  its/ruling/src/test/expected/go-S100.json
  its/ruling/src/test/expected/go-S103.json
  its/ruling/src/test/expected/go-S1135.json
  its/ruling/src/test/expected/go-S1186.json
  its/ruling/src/test/expected/go-S126.json
  its/ruling/src/test/expected/go-S138.json
  its/ruling/src/test/expected/go-S1479.json
  its/ruling/src/test/expected/go-S3776.json
  its/ruling/src/test/java/org/sonar/go/GoRulingTest.java
  sonar-go-plugin/src/main/java/org/sonar/go/plugin/GoChecks.java
  sonar-go-plugin/src/main/resources/org/sonar/l10n/go/rules/go/S1186.html
  sonar-go-plugin/src/main/resources/org/sonar/l10n/go/rules/go/S1186.json
  sonar-go-plugin/src/main/resources/org/sonar/l10n/go/rules/go/Sonar_way_profile.json
Labels: review

#275 Rule S1066: Collapsible 'if' statements should be merged
  common-rule-engine/src/main/java/org/sonar/commonruleengine/checks/CollapsibleIfCheck.java
  common-rule-engine/src/test/files/checks/CollapsibleIfCheck/CollapsibleIfCheck.go
  common-rule-engine/src/test/files/checks/CollapsibleIfCheck/CollapsibleIfCheck.java
  common-rule-engine/src/test/java/org/sonar/commonruleengine/checks/CollapsibleIfCheckTest.java
  its/ruling/src/test/expected/go-S1066.json
  sonar-go-plugin/src/main/java/org/sonar/go/plugin/GoChecks.java
  sonar-go-plugin/src/main/resources/org/sonar/l10n/go/rules/go/S1066.html
  sonar-go-plugin/src/main/resources/org/sonar/l10n/go/rules/go/S1066.json
  sonar-go-plugin/src/main/resources/org/sonar/l10n/go/rules/go/Sonar_way_profile.json
Labels: in progress

#278 Rule S1192: String literals should not be duplicated
  common-rule-engine/src/main/java/org/sonar/commonruleengine/checks/StringLiteralDuplicatedCheck.java
  common-rule-engine/src/test/files/checks/StringLiteralDuplicatedCheck/StringLiteralDuplicatedCheck.go
  common-rule-engine/src/test/files/checks/StringLiteralDuplicatedCheck/StringLiteralDuplicatedCheckCustom.go
  common-rule-engine/src/test/java/org/sonar/commonruleengine/checks/StringLiteralDuplicatedCheckTest.java
  its/ruling/src/test/expected/go-S1192.json
  sonar-go-plugin/src/main/java/org/sonar/go/plugin/GoChecks.java
  sonar-go-plugin/src/main/resources/org/sonar/l10n/go/rules/go/S1192.html
  sonar-go-plugin/src/main/resources/org/sonar/l10n/go/rules/go/S1192.json
  sonar-go-plugin/src/main/resources/org/sonar/l10n/go/rules/go/Sonar_way_profile.json
Labels: in progress

#281 Fix #78 RSPEC-1145 useless if(true) and if(false)
  common-rule-engine/src/main/java/org/sonar/commonruleengine/checks/UselessIfCheck.java
  common-rule-engine/src/test/files/checks/UselessIfCheck/UselessIfCheck.go
  common-rule-engine/src/test/java/org/sonar/commonruleengine/checks/UselessIfCheckTest.java
  its/ruling/src/test/expected/go-S1145.json
  sonar-go-plugin/src/main/java/org/sonar/go/plugin/GoChecks.java
  sonar-go-plugin/src/main/resources/org/sonar/l10n/go/rules/go/S1145.html
  sonar-go-plugin/src/main/resources/org/sonar/l10n/go/rules/go/S1145.json
Labels: in progress

#279 Rule S104: Files should not have too many lines of code
  common-rule-engine/src/main/java/org/sonar/commonruleengine/checks/TooManyLinesInFileCheck.java
  common-rule-engine/src/test/files/checks/TooManyLinesInFileCheck/TooManyLinesInFileCheck.go
  common-rule-engine/src/test/files/checks/TooManyLinesInFileCheck/TooManyLinesInFileCheckCompliant.go
  common-rule-engine/src/test/files/checks/TooManyLinesInFileCheck/TooManyLinesInFileCheckCustom.go
  common-rule-engine/src/test/java/org/sonar/commonruleengine/checks/TooManyLinesInFileCheckTest.java
  its/ruling/src/test/expected/go-S104.json
  sonar-go-plugin/src/main/java/org/sonar/go/plugin/GoChecks.java
  sonar-go-plugin/src/main/resources/org/sonar/l10n/go/rules/go/S104.html
  sonar-go-plugin/src/main/resources/org/sonar/l10n/go/rules/go/S104.json
Labels: in progress

#282 Rule S1871: Two branches in a conditional structure should not have exactly the same implementation
  build.gradle
  common-rule-engine/src/main/java/org/sonar/commonruleengine/checks/TwoBranchesAreIdenticalCheck.java
  common-rule-engine/src/test/files/checks/TwoBranchesAreIdenticalCheck/TwoBranchesAreIdenticalCheck.go
  common-rule-engine/src/test/java/org/sonar/commonruleengine/checks/TwoBranchesAreIdenticalCheckTest.java
  its/ruling/src/test/expected/go-S1871.json
  sonar-go-plugin/src/main/java/org/sonar/go/plugin/GoChecks.java
  sonar-go-plugin/src/main/resources/org/sonar/l10n/go/rules/go/S1871.html
  sonar-go-plugin/src/main/resources/org/sonar/l10n/go/rules/go/S1871.json
  sonar-go-plugin/src/main/resources/org/sonar/l10n/go/rules/go/Sonar_way_profile.json
Labels: in progress

#286 Rule S1151: "switch case" clauses should not have too many lines
  common-rule-engine/src/main/java/org/sonar/commonruleengine/checks/SwitchCaseTooBigCheck.java
  common-rule-engine/src/test/files/checks/SwitchCaseTooBigCheck/SwitchCaseTooBigCheck.go
  common-rule-engine/src/test/files/checks/SwitchCaseTooBigCheck/SwitchCaseTooBigCheckMax3.go
  common-rule-engine/src/test/java/org/sonar/commonruleengine/checks/SwitchCaseTooBigCheckTest.java
  its/ruling/src/test/expected/go-S1151.json
  sonar-go-plugin/src/main/java/org/sonar/go/plugin/GoChecks.java
  sonar-go-plugin/src/main/resources/org/sonar/l10n/go/rules/go/S1151.html
  sonar-go-plugin/src/main/resources/org/sonar/l10n/go/rules/go/S1151.json
Labels: in progress

#289 Rule S134: Control flow statements should not be nested too deeply
  common-rule-engine/src/main/java/org/sonar/commonruleengine/checks/NestedControlFlowCheck.java
  common-rule-engine/src/test/files/checks/NestedControlFlowCheck/NestedControlFlowCheck.go
  common-rule-engine/src/test/files/checks/NestedControlFlowCheck/NestedControlFlowCheckCustom.go
  common-rule-engine/src/test/java/org/sonar/commonruleengine/checks/NestedControlFlowCheckTest.java
  its/ruling/src/test/expected/go-S134.json
  sonar-go-plugin/src/main/java/org/sonar/go/plugin/GoChecks.java
  sonar-go-plugin/src/main/resources/org/sonar/l10n/go/rules/go/S134.html
  sonar-go-plugin/src/main/resources/org/sonar/l10n/go/rules/go/S134.json
Labels: in progress

#288 Rule S1172: Unused function parameters should be removed
  common-rule-engine/src/main/java/org/sonar/commonruleengine/checks/UnusedParameterCheck.java
  common-rule-engine/src/test/files/checks/UnusedParameterCheck/UnusedParameterCheck.go
  common-rule-engine/src/test/java/org/sonar/commonruleengine/checks/UnusedParameterCheckTest.java
  its/ruling/src/test/expected/go-S1172.json
  sonar-go-plugin/src/main/java/org/sonar/go/plugin/GoChecks.java
  sonar-go-plugin/src/main/resources/org/sonar/l10n/go/rules/go/S1172.html
  sonar-go-plugin/src/main/resources/org/sonar/l10n/go/rules/go/S1172.json
  sonar-go-plugin/src/main/resources/org/sonar/l10n/go/rules/go/Sonar_way_profile.json
Labels: in progress

#293 update ruling (after vendor exclusion)
  its/ruling/src/test/expected/go-S1172.json
  its/ruling/src/test/expected/go-S134.json
  its/ruling/src/test/expected/go-S3981.json
Labels: in progress

#291 Rule S1994: for loop increment clauses should modify the loops' counters
  common-rule-engine/src/main/java/org/sonar/commonruleengine/checks/ForLoopConditionVariableCheck.java
  common-rule-engine/src/test/files/checks/ForLoopConditionVariableCheck/ForLoopConditionVariableCheck.go
  common-rule-engine/src/test/java/org/sonar/commonruleengine/checks/ForLoopConditionVariableCheckTest.java
  its/ruling/src/test/expected/go-S1994.json
  its/ruling/src/test/java/org/sonar/go/GoRulingTest.java
  sonar-go-plugin/src/main/java/org/sonar/go/plugin/GoChecks.java
  sonar-go-plugin/src/main/resources/org/sonar/l10n/go/rules/go/S1994.html
  sonar-go-plugin/src/main/resources/org/sonar/l10n/go/rules/go/S1994.json
  sonar-go-plugin/src/main/resources/org/sonar/l10n/go/rules/go/Sonar_way_profile.json
Labels: in progress
